filebeat.modules: 
  - module: kafka 
    log: 
      enabled: true 
      var.kafka_home: 
          /usr/local/kafka 
      var.paths: 
        - "/usr/local/kafka/logs/controller.log*" 
        - "/usr/local/kafka/logs/server.log*" 
        - "/usr/local/kafka/logs/state-change.log*" 
        - "/usr/local/kafka/logs/kafka-*.log*" 
  - module: system 
    syslog: 
      enabled: true 
output.elasticsearch: 
  enabled: true 
  hosts: ["10.36.9.89:9200"] 
setup.kibana: 
  host: "10.36.9.215:30001" 
  protocol: "http"
